### ISSUE TITLE
model load error

### ISSUE THREAD

**Issue by stojakovic312636841** [YBIGTA/pytorch-hair-segmentation#26]
use command:
python3 evaluate.py   --networks pspnet_resnet101   --ckpt_dir ./models/pspnet_resnet101_sgd_lr_0.002_epoch_100_test_iou_0.918.pth   --dataset figaro   --data_dir ./data/Figaro1k   --save_dir ./overlay   --use_gpu True

but,call back
Traceback (most recent call last):
  File "evaluate.py", line 51, in <module>
    state = torch.load(ckpt_dir)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 367, in load
    return _load(f, map_location, pickle_module)
  File "/usr/local/lib/python3.5/dist-packages/torch/serialization.py", line 528, in _load
    magic_number = pickle_module.load(f)
_pickle.UnpicklingError: invalid load key, 'v'.

how to solve this error

thank you for your work!

**Comment by q5390498** [comment]
same problem. Can you tell me how to slove this problem? thank you very much

**Comment by Jooong** [comment]
@stojakovic312636841 @q5390498 According to the comment [here](https://stackoverflow.com/questions/8111078/unpicklingerror-invalid-load-key/20874146), this might be related to git-lfs. Check if the model files are properly cloned. You can run `ls -al` and check the file size. If they aren't properly cloned, you should install git-lfs and follow instructions [here](https://github.com/git-lfs/git-lfs/issues/325).
