### ISSUE TITLE
TypeError: Can't instantiate abstract class Accuracy with abstract methods resetTypeError: Can't instantiate abstract class Accuracy with abstract methods reset

### ISSUE THREAD

**Issue by mabdullahrafique** [YBIGTA/pytorch-hair-segmentation#29]
I am running the program when I enter ignite market False the training happens without any problem, but when I set ignite True it gives the following error
**File "main.py", line 111, in main
    logger=logger)
  File "/home/abdullah/Documents/Company Work/Segmentation/pytorch-hair-segmentation-master/utils/trainer_verbose.py", line 106, in train_with_ignite
    'pix-acc': Accuracy(measure),
TypeError: Can't instantiate abstract class Accuracy with abstract methods reset**

Please help me how can I get over it

**Comment by duchengyao** [comment]
the same error

**Comment by davinnovation** [comment]
Our ignite_code works with pytorch-ignite 0.1.0
In our test, failed with the reported error on 0.1.2. Please downgrade ignite version to 0.1.0. Thx for report

**Comment by nidetaoge** [comment]
Sorry to bother, but I have found that even though pytorch-ignite's version is 0.1.0, this problem still exists, can you help me with this? 
![image](https://user-images.githubusercontent.com/12149807/58005603-98881f00-7b18-11e9-85ba-d4582b4ef89b.png)

**Comment by nidetaoge** [comment]
> Sorry to bother, but I have found that even though pytorch-ignite's version is 0.1.0, this problem still exists, can you help me with this?
> ![image](https://user-images.githubusercontent.com/12149807/58005603-98881f00-7b18-11e9-85ba-d4582b4ef89b.png)

More test, python3 is not ok like what upper said, but python2 works fine. And when workers set to be 0(memory), the result turns out to be several nan like this:
![image](https://user-images.githubusercontent.com/12149807/58008885-e81e1900-7b1f-11e9-8202-228b3d1bee62.png)
