### ISSUE TITLE
how to run evaluate.py

### ISSUE THREAD

**Issue by bottlesunny** [YBIGTA/pytorch-hair-segmentation#42]
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by wubaoyuan** [comment]
I got the same error

**Comment by wubaoyuan** [comment]
@bottlesunny I have solved this issue. The reason is that the ckpt file  ./pth is not really downloaded after git clone. You can download it directly, then copy it to ./models.

**Comment by bottlesunny** [comment]
Very useful，cheers

**Comment by Jooong** [comment]
@wubaoyuan @bottlesunny please refer to [issue #37](https://github.com/YBIGTA/pytorch-hair-segmentation/issues/37). I'll close this issue.
