### ISSUE TITLE
Hi does this model generalize?

### ISSUE THREAD

**Issue by eipeace2u** [YBIGTA/pytorch-hair-segmentation#50]
https://github.com/YBIGTA/pytorch-hair-segmentation/blob/b31f7a1bf0151e73791ddf33f49c32a2d13c4984/data/figaro.py#L24

How can we extrapolate this model to jpgs outside the dataset?  It looks like it relies on masks existing which does not make for a generic model.

**Comment by Jooong** [comment]
I added a script in the [latest commit](https://github.com/YBIGTA/pytorch-hair-segmentation/commit/84253af697151fc73e36e8aef8b8f652fa548453). Please try with demo.py
