### ISSUE TITLE
invalid load key, 'v'. when running demo.py

### ISSUE THREAD

**Issue by mxgbs** [YBIGTA/pytorch-hair-segmentation#54]
Hi,

I tried to run demo.py for some data. However, I got following error. Could you please help with this? Thank you

python3 demo.py \
--ckpt_dir ./models/pspnet_resnet101_sgd_lr_0.002_epoch_100_test_iou_0.918.pth \
--img_dir xxx/pytorch-hair-segmentation/data/images \
--networks pspnet_resnet101 \
--save_dir xxx/pytorch-hair-segmentation/data/result \
--use_gpu True
Traceback (most recent call last):
  File "demo.py", line 51, in <module>
    state = torch.load(ckpt_dir)
  File "/local/mnt/workspace2/yandeng/anaconda2/envs/pytorch344/lib/python3.6/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/local/mnt/workspace2/yandeng/anaconda2/envs/pytorch344/lib/python3.6/site-packages/torch/serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

My conda environment is as following

certifi               2019.11.28
cffi                  1.14.0
mkl-fft               1.0.15
mkl-random            1.1.0
mkl-service           2.3.0
numpy                 1.18.1
olefile               0.46
opencv-contrib-python 3.4.4.19
Pillow                7.0.0
pip                   20.0.2
pycparser             2.19
pytorch-ignite        0.3.0
setuptools            45.2.0.post20200210
six                   1.14.0
torch                 1.4.0
torchvision           0.5.0
wheel                 0.34.2

I tried to install the default environment; however many are legacy versions which seems not be able correctly installed.

**Comment by lartpang** [comment]
Me too! :<

**Comment by lartpang** [comment]
Ok, I have known the reason. Because, when we `git clone` the repository to our disk, the model files of the folder `model` is only empty (the size of these files is larger than the limitaion of `git`...). You can try the command `ls -lh` to see the file size, and the size is very small.
We can use `wget` or other tools to download the real file in https://github.com/YBIGTA/pytorch-hair-segmentation/tree/master/models into the folder `model`...
Good Luck!

**Comment by Jooong** [comment]
I just uploaded checkpoints to google drive and now you can download it via links in the readme.
