### ISSUE TITLE
this repository is over its data quota

### ISSUE THREAD

**Issue by bizerfr** [YBIGTA/pytorch-hair-segmentation#57]
Hi, I try to git clone this repo, but I cannot get the right model files. It says "This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access". Could you please upload the pth file in the google drive?
Thanks.

**Comment by Jooong** [comment]
Thanks for letting us know. I just uploaded checkpoint files to gdrive and added links to readme.
