### ISSUE TITLE
The license of models' weight (checkpoint)

### ISSUE THREAD

**Issue by mamo3gr** [YBIGTA/pytorch-hair-segmentation#59]
Dear authors, 

Thank you for great works in this repository.
License of models' weight (checkpoints) that are linked from README.md is MIT as well as source codes in this repository, isn't it?

Regards,

**Comment by Jooong** [comment]
Hi @mamo3gr , yes you're right.

**Comment by mamo3gr** [comment]
Thank you for rapid response!
