### ISSUE TITLE
Reproducing [Real-time-deep-hair-matting-on-mobile-devices](https://github.com/YBIGTA/pytorch-hair-segmentation/wiki/Real-time-deep-hair-matting-on-mobile-devices)

### ISSUE THREAD

**Issue by Jooong** [YBIGTA/pytorch-hair-segmentation#7]

**Comment by davinnovation** [comment]
commit 4f0975d177883d5e2cb525b6453db1137f33f899

**Comment by Shreeyak** [comment]
@Jooong Hey, did you reproduce the real-time hair matting paper? I don't see mobilenet in the models folder. 
How would I use your repo to train the above paper on my own dataset?
